### ISSUE TITLE
metrics publishing mechanism

### ISSUE THREAD

**Issue by georgej-github** [newrelic/micrometer-registry-newrelic#109]
Documentation for [Micrometer's NewRelic Meter registry](https://micrometer.io/docs/registry/new-relic) has this:
```
New Relic Insights operates on a push model. 
Some features of NRQL assume that Insights receives a distinct event payload for every timing, count, etc. 
Micrometer instead ships aggregates at a prescribed interval, 
allowing your app’s throughput to scale without concern for event propagation to Insights becoming a bottleneck.
```
Does the same apply when using NewRelic's meter registry?  Are metrics shipped at a prescribed interval or is a payload sent for each event of a timing, counter etc. ?

**Comment by breedx-nr** [comment]
Hey @georgej-github thanks for the question.  The short answer is yes -- metrics are shipped at an interval.

The `NewRelicRegistry` extends the `StepMeterRegistry` which extends `PushMeterRegistry`.
I the [source code for the `PushMeterRegistry`](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushMeterRegistry.java#L74) you can see here that the `publishSafely()` method (which calls `publish()`) is scheduled to run at a fixed rate based on the configuration.

Between publishes, the metrics are buffered by the `NewRelicRegistry`.

Does that answer your question?

**Comment by georgej-sportsbet** [comment]
Thanks for clarifying @breedx-nr.

**Comment by georgej-github** [comment]
Thanks for clarifying @breedx-nr .

**Comment by breedx-nr** [comment]
Excellent. Thanks again!
