### ISSUE TITLE
Update SpringConfig Wiki as per v0.6.0

### ISSUE THREAD

**Issue by spatanjali** [newrelic/micrometer-registry-newrelic#111]
Since the PR #104 brings in the changes to the package where the Config classes are residing, the corresponding "import" statements as mentioned below needs to be updated in the sample wiki page: https://github.com/newrelic/micrometer-registry-newrelic/wiki/Spring-Config-Example

**Remove**
```
import io.micrometer.newrelic.NewRelicRegistry;
import io.micrometer.NewRelicRegistryConfig;
```

**Replace**
```
import com.newrelic.telemetry.micrometer.NewRelicRegistry;
import com.newrelic.telemetry.micrometer.NewRelicRegistryConfig;

```

**Comment by breedx-nr** [comment]
Looks good, thanks for pointing that out.  Please have a look at the updated wiki and reopen if it doesn't look good.  👍
