### ISSUE TITLE
Improve configurability of metric granularity

### ISSUE THREAD

**Issue by jodeev** [newrelic/micrometer-registry-newrelic#124]
We need to indicate the granularity of the metrics and whether it is configurable. 

Our metrics are less granular than others by default. Compare the charts in the [signalFx description](https://micrometer.io/docs/registry/signalFx) and the [NR description](https://micrometer.io/docs/registry/new-relic) for exactly the same content.

Data from this registry is smoothed out over a minute, only get average and max times. Would like more granularity. 

If it is possible to configure - through spring configuration, or on our registry, add this to our readme. 

The default should be higher granularity.

**Comment by kford-newrelic** [comment]
De-prioritized.
