### ISSUE TITLE
Custom Attribute addition to Metric Table Not Possible?

### ISSUE THREAD

**Issue by priyachhatwal-block1** [newrelic/micrometer-registry-newrelic#129]
The problem statement is that we are unable to monitor metrics for micros services based on namespaces. 

**Just a view of the current setup:**
We have several namespaces (environments) running in our non-prod K8 clusters. Data of all those is pumped to B1X account in NR
There are some namespaces that are used to logically split our dev, staging and pre-prod environments
Each of these namespaces has its own set of the same microservices running in it. For example; "microservice1-dev" and "microservice2-dev" on dev, "microservice1-staging" and "microservice2-staging" on staging and so on
What we need are separate micrometer dashboards for each of the environments to visualize services performance in each. Hope this clarifies our requirement.

Our system provides lots of logs to Newrelic as part of which the namespace is one of the values too. However, the Metric table doesnt seem to expose the Namespace value and doesnt seem to allow addition of custom attributes to metric table too.

Please can you check on this

**Comment by kford-newrelic** [comment]
@priyachhatwal-block1 thank you for this suggested feature. Unfortunately, we do not have the engineering capacity to take up this request. If you are ever interested enough to do some agent coding however, we would gladly review any PR you could submit.
