### ISSUE TITLE
resolve Snyk warnings in test dependency mockserver-netty

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/micrometer-registry-newrelic#132]
https://github.com/newrelic/micrometer-registry-newrelic/pull/131/checks?check_run_id=2788830865

two security warnings in a test dependency. I've submitted a support ticket to snyk because the UI does not reflect the latest in the repo. Also, the only fix right now for those two are to temporarily ignore them.

**Comment by kford-newrelic** [comment]
Not selected for the agent roadmap.
