### ISSUE TITLE
Export LongTaskTimer.max to newrelic

### ISSUE THREAD

**Issue by Nazukin-Dmitry** [newrelic/micrometer-registry-newrelic#136]
Hello.

It would be helpfull if value of _LongTaskTimer.max_ was exported to newrelic. When we have same method executed in parallel, max value is more important than total duration, because it gives information about slowest task(or first started task).

**Comment by kford-newrelic** [comment]
@Nazukin-Dmitry thanks for the suggested enhancement! Unfortunately, we have limited engineering bandwidth and this wasn't selected for the agent roadmap.

**Comment by Nazukin-Dmitry** [comment]
@kford-newrelic How do you feel if I would prepare pull request by myself?

**Comment by kford-newrelic** [comment]
@Nazukin-Dmitry that would be great - we'd be eager to review it!
