### ISSUE TITLE
Add custom internal "tag" to indicate micrometer source

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/micrometer-registry-newrelic#21]
We should "tag" all metrics coming from the micrometer exporter with a custom common attribute that indicates that the metric came from a micrometer application.

There is a data model doc that describes the convention for tags.

instrumentation.provider should be set to "micrometer"
collector.name should be set to "micrometer-registry-newrelic"

**Comment by jkwatson** [comment]
add a `newRelic.metricSourceLibrary=micrometer` attribute, maybe?
