### ISSUE TITLE
Add spring autoconfiguration classes

### ISSUE THREAD

**Issue by jkwatson** [newrelic/micrometer-registry-newrelic#5]
Problem: 

Users need to add glue code so that our Micrometer exporter will work with their Spring applications. 

Spring has autoconfiguration capabilities.  If our Micrometer exporter can tap into the Spring autoconfiguration API, then customers will not need to add glue code. Micrometer exporter should connect automatically. 

Hand wavey here - not sure how much glue code will be removed and what will still be necessary.

**Comment by kford-newrelic** [comment]
@totof3110 apologies but we will not be able to dedicate engineering time to this enhancement (though it's a good one!). Not selected for the agent roadmap.
