### ISSUE TITLE
Does this fully replace the New Relic java agent?

### ISSUE THREAD

**Issue by 2ZZ** [newrelic/micrometer-registry-newrelic#68]
Hi, quick question, does this package fully replace the New Relic java agent or should they both be used in conjunction?

**Comment by jkwatson** [comment]
Hello, @2ZZ !  This definitely does not fully replace the New Relic agent. Micrometer only includes metrics, and no distributed-tracing spans, so you would only get micrometer metrics flowing into New Relic. You *can* use the two in conjunction, however. 

What sort of application are you looking to monitor? [i.e. is it a backend batch process, or an http service, or whatever...]. Is it spring-boot, or are you using micrometer as a stand-alone metrics library?

Thanks for the question!

**Comment by 2ZZ** [comment]
Hi @jkwatson, thanks for your answer
It is a spring app. I found using this extension alone Micrometer was only reporting events into the collector and not metrics, It wasn't until I added the java agent that JVM metrics began to flow through as well. 
I wasn't sure if by adding both there would be any duplication, or possibly I could remove the java agent with some reconfiguration of Micrometer.

**Comment by jkwatson** [comment]
There might be some duplication if you use both. the agent is definitely more full-featured and comprehensive, however. I recommend running both together and seeing if you find value in the dimensional metrics coming out of micrometer.

**Comment by jkwatson** [comment]
Closing this, as the question has been answered.
