### ISSUE TITLE
Allow attributes to be added after NewRelicRegistry is initialized

### ISSUE THREAD

**Issue by mike-traff-paypay** [newrelic/micrometer-registry-newrelic#76]
It would be helpful if NewRelicRegistry followed Micrometer conventions and allowed for additional configuration after instantiation.  Specifically, you should be able to add common attributes with a MeterRegistryCustomizer like so:

```
@Bean
MeterRegistryCustomizer<NewRelicRegistry> newRelicMetricsCommonAttributes() {
    return registry -> registry.config().commonAttributes(
        new Attributes()
                    .put(HOST, InetAddress.getLocalHost().getHostName())
                    ...
    );
  }
```
Convention is documented [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-getting-started).

**Comment by breedx-nr** [comment]
Hi @mike-traff-paypay.  Sorry that this has been sitting here untouched.  We like this idea and want to look into addressing this and making it more conventional.  If you are interested in working on this before we can get to it, we are happy to discuss and/or review your pull request.

**Comment by fieldju** [comment]
@breedx-nr @mike-traff-paypay 

As far as I can tell this registry supports the standard Micrometer post create add common tags pattern just fine out of the box.

```java
package io.armory.plugin.observability.newrelic;

import io.armory.plugin.observability.model.PluginConfig;
import io.armory.plugin.observability.model.PluginMetricsNewRelicConfig;
import io.armory.plugin.observability.service.MeterFilterService;
import io.armory.plugin.observability.service.TagsService;
import io.micrometer.newrelic.NewRelicRegistry;
import java.util.concurrent.Executors;
import java.util.function.Supplier;

public class NewRelicRegistrySupplier implements Supplier<NewRelicRegistry> {

  private final PluginMetricsNewRelicConfig newRelicConfig;
  private final TagsService tagsService;
  private final MeterFilterService meterFilterService;

  public NewRelicRegistrySupplier(
      PluginConfig pluginConfig, TagsService tagsService, MeterFilterService meterFilterService) {

    newRelicConfig = pluginConfig.getMetrics().getNewrelic();
    this.tagsService = tagsService;
    this.meterFilterService = meterFilterService;
  }

  @Override
  public NewRelicRegistry get() {
    if (!newRelicConfig.isEnabled()) {
      return null;
    }

    var config = new NewRelicRegistryConfig(newRelicConfig);
    var registry = new NewRelicRegistry.NewRelicRegistryBuilder(config).build();

    registry.config().commonTags(tagsService.getDefaultTags());
    meterFilterService
        .getMeterFilters()
        .forEach(meterFilter -> registry.config().meterFilter(meterFilter));

    registry.gauge(
        "metrics.dpm",
        registry,
        reg -> reg.getMeters().size() * (60d / newRelicConfig.getStepInSeconds()));

    registry.start(Executors.defaultThreadFactory());
    return registry;
  }
}
```

This is what I am doing in a plugin that I am working on, which is why this is wrapped in a supplier object in case you are curious.

It seems like the attributes are just an additional way to supply non - `<String, String>` attributes such as booleans and numbers.

These tags show up as expected:
![image](https://user-images.githubusercontent.com/711726/85208581-8a419f00-b2e6-11ea-8212-b1121a506293.png)

**Comment by breedx-nr** [comment]
@fieldju Oh that's great to hear!  @mike-traff-paypay what do you think?  Does that work for you?

**Comment by breedx-nr** [comment]
@mike-traff-paypay Please reopen with comments if this approach does not work for you.  Thanks again to @fieldju !
