### ISSUE TITLE
Prevent NewRelicRegistry's telemetryClient from running forever when NewRelic returns 429

### ISSUE THREAD

**Issue by vsanna** [newrelic/micrometer-registry-newrelic#80]
Hi there,

Let me open an issue for how NewRelicRegistry uses TelemetryClient.

## Background
When NewRelic returns 429 status code, TelemetryClient which NewRelicRegistry uses seems to try to throw RetryWithRequestedWaitException and retry sending metrics.
However, in the retry action, any kind of function considering retryCount like BackOff are not used and TelemetryClient's executor actually repeats these steps below
- scheduleBatchSend
- sendWithErrorHandling
- retry
- scheduleBatchSend
This, for example, prevents JVM from shutting down because TelemetryClient's executor keeps on creating non-daemon threads to retry during it gets 429 from NewRelic.

## Suggestion
As APM provides send_data_on_exit, how about introducing some function which stops TelemetryClient' executor when any applications do shutdown.
For example, when NewRelicRegistry does close/stop, it also should shutdown its TelemetryClient.

Or please make it possible to call TelemetryClient's shutdown method from application side(It's private field and NewRelicRegister builder doesn't provide us a way to inject TelemetryClient.)

## ref
https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file#cfg-send_data_on_exit

**Comment by jeffalder** [comment]
@vsanna Great catch. Do you want to submit a PR with a proposed fix? I think the appropriate answer is what you suggested:

> when NewRelicRegistry does close/stop, it also should shutdown its TelemetryClient.

`NewRelicRegistry` inherits `stop` from `PushMeterRegistry`. It seems reasonable that `NewRelicRegistry` should override `stop` and call `shutdown()` on the `TelemetryClient`.

**Comment by vsanna** [comment]
@jeffalder thank you! I will open a PR later with that fix

**Comment by breedx-nr** [comment]
relates to https://github.com/newrelic/newrelic-telemetry-sdk-java/issues/167

**Comment by breedx-nr** [comment]
The close behavior is now merged.  The 429 handling will be addressed in the telemetry sdk (see https://github.com/newrelic/newrelic-telemetry-sdk-java/issues/189)
