### ISSUE TITLE
Provide a quickstart/getting-started

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/micrometer-registry-newrelic#81]
We should make it easier for users to get started quickly with this exporter.  We should show clear, common examples of how to wire it up with code samples and pictures.

**Comment by jodeev** [comment]
We have more feedback that we need some improved documentation in the README or New Relic docs for instrumentation, and also for examples of NRQL queries.  

The Micrometer page on docs.newrelic is out of date. The Github README sends the user to New Relic docs, which do not provide sufficient guidance.

**Comment by luketn** [comment]
@kford-newrelic what's with the wontfix label - it would be great to have some better docs no?

**Comment by kford-newrelic** [comment]
@luketn it's a great suggestion but unfortunately, we're not in a position to dedicate engineering time to it. Not selected for the agent roadmap.
