### ISSUE TITLE
Timer data unusable in NRQL to create dashboards?

### ISSUE THREAD

**Issue by fieldju** [newrelic/micrometer-registry-newrelic#84]
According to a senior community manager the way this integration is shipping data to New Relic is unusable in NRQL to create dashboards for request latency.

I am seeing data like the following

```json
{
      "account": "None",
      "applicationName": "clouddriver",
      "armoryAppVersion": "2.21.0-snapshot.20200616060900.uncommitted.916e8ee",
      "baseUnit": "milliseconds",
      "cause": "None",
      "collector.name": "micrometer-registry-newrelic",
      "collector.version": "0.5.0",
      "controller": "PrometheusScrapeController",
      "controller.invocations": {
        "type": "summary",
        "count": 33,
        "sum": 72.189644,
        "min": null,
        "max": 2.47281
      },
      "customerEnvName": "fieldju-local",
      "customerName": "armory",
      "endTimestamp": 1592601631422,
      "instrumentation.provider": "micrometer",
      "lib": "armory-observability-plugin",
      "libVersion": "v1.0.0-SNAPSHOT",
      "method": "scrape",
      "metricName": "controller.invocations",
      "newrelic.source": "metricAPI",
      "ossAppVersion": "6.9.2-20200606020017",
      "region": "None",
      "spinnakerRelease": "1.20.5",
      "status": "2xx",
      "statusCode": "200",
      "success": "true",
      "timestamp": 1592601613053
    }
```

According to [this discuss Newrelic post](https://discuss.newrelic.com/t/how-to-process-summary-metric-data-and-display-charts/101693/7) data like the following and above cannot but used to create charts?
![image](https://user-images.githubusercontent.com/711726/85182324-34fd8300-b23d-11ea-8d43-c353803705bc.png) 

If this is true, I am wondering why you moved from gauges to summaries in 0.4.0?

**Comment by fieldju** [comment]
Okay, I think I have it figured out.

    SELECT (sum(controller.invocations)/count(controller.invocations)) 
    FROM Metric 
    WHERE metricName = 'controller.invocations' 
        AND statistic != 'percentile' 
    SINCE 30 minutes ago 
    FACET controller, method 
    TIMESERIES AUTO 

This is what I had to do and I was able to create a chart with the summary data.

I would say that response of that discussion post was not accurate.

It appears I can access Summary attributes via treating each attribute as a NRQL function.

    ${atribute}(metric_name_that_is_a_summery)

**Comment by fieldju** [comment]
For the next engineer to find this :).

NRQL is smart enough to rewrite

```sql
SELECT (sum(controller.invocations)/count(controller.invocations)) 
FROM Metric 
WHERE metricName = 'controller.invocations' 
    AND statistic != 'percentile' 
SINCE 30 minutes ago 
FACET controller, method 
TIMESERIES AUTO 
```

as

```sql
SELECT average(controller.invocations)
FROM Metric 
WHERE metricName = 'controller.invocations' 
    AND statistic != 'percentile' 
SINCE 30 minutes ago 
FACET controller, method 
TIMESERIES AUTO 
```

That will give you the rate of the summary event/metric

**Comment by jkwatson** [comment]
FYI, @fieldju, I think you can also leave out the `metricName = 'controller.invocations'` as that is implied by the selection itself.  So, this should work:

```
SELECT average(controller.invocations)
FROM Metric 
WHERE statistic != 'percentile' 
SINCE 30 minutes ago 
FACET controller, method 
TIMESERIES AUTO 
```
