### ISSUE TITLE
Transaction breakdown table

### ISSUE THREAD

**Issue by enesaltinok** [newrelic/micrometer-registry-newrelic#87]
Hi,

If we use micrometer-registry-newrelic, are we able to see the redis transaction details in the breakdown table?

**Comment by victorNewRelic** [comment]
Hi @enesaltinok - Sounds like you're using the New Relic agent and the Micrometer registry together. Is that right? Are you referring to the Transaction breakdown table? If so, the New Relic agent creates Redis metrics and includes them in the table. We're not able to scope the Micrometer metric creation to the New Relic transaction. What extra information would you get if there was a way to correlate Micrometer Redis metrics to the transaction?

**Comment by enesaltinok** [comment]
I am using new relic agent and planning to use the micrometer registry. New relic agent won't create redis metrics because it does not support Redisson; it only supports jedis: https://discuss.newrelic.com/t/feature-idea-instrumentation-support-for-redisson-client-in-java-agent/51690 
I want to observe which web transactions spend how much time on redis.

**Comment by jkwatson** [comment]
As @victorNewRelic mentioned, we don't currently have a way to put micrometer metrics into the transaction breakdown like this. this mixed-mode use-case is an interesting one, though. Thanks for bringing it up!

**Comment by subvocal** [comment]
@enesaltinok - I spoke with our Java agent team and found that we have a NR Java agent instrumentation module for Redisson that will be available as an open source project soon. If you shoot me a note to vsoares@newrelic.com, I can get you early access to it or let you know when it's available publicly.

**Comment by breedx-nr** [comment]
I think that we have answered this question.
