### ISSUE TITLE
Filter NaN values for a gauge

### ISSUE THREAD

**Issue by amalinovskiy** [newrelic/micrometer-registry-newrelic#94]
Currently there is no straight forward way to filter NaN values from a micrometer Gauge (which can be used e.g. to not send values which are too small to be of interest). The only way to do it is to extend the NewRelicReigstry and reimplement the publish method - which due to visibility of constructors and builder methods leads to reimplementing almost everything there.

Filtering the NaNs could be either done always or be a configurable flag. Alternatively NewRelicRegistry can be changed to be more inheritance friendly.

The always filtering in publish method is very straightforward:
```     
     double value = ((Gauge) meter).value();
     if (Double.isFinite(value)) {
          metrics.add(gaugeTransformer.transform(value);
     }
```

**Comment by jeffalder** [comment]
I'm assuming you'd like to prevent NaN values from getting transmitted to the backend? That filtering is happening in the Telemetry SDK, which this should be using: https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/main/telemetry_core/src/main/java/com/newrelic/telemetry/json/AttributesJson.java#L46 for attributes and https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/main/telemetry_core/src/main/java/com/newrelic/telemetry/metrics/json/MetricToJson.java#L94 for values.

Are you having problems where that's not working?

**Comment by jeffalder** [comment]
Actually, here's where we filter out gauges with invalid values: https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/main/telemetry_core/src/main/java/com/newrelic/telemetry/metrics/json/MetricBatchJsonTelemetryBlockWriter.java#L49

**Comment by amalinovskiy** [comment]
my bad - i did not realise it was filtered out later on and the problem was different for me, thanks!
